export const guestCopy = {
  en: {
    language: "العربية",
    menu: "Menu",
    cart: "Cart",
    checkout: "Checkout",
    track: "Track order",
    add: "Add to cart",
    total: "Total",
    yourName: "Your name",
    nameHint: "Shown on the shared table cart",
    pin: "Table PIN",
    pinHint: "Enter the table PIN to join from outside the restaurant",
    outside: "This location is outside the branch. Enter the table PIN, then join.",
    badPin: "That PIN is not valid. Ask the branch for the current table PIN.",
    tableCodeFailed: "This table code isn't working. Please ask a staff member.",
    useLocation: "Use my location",
    join: "Join this table",
    verifying: "Checking the table…",
    emptyCart: "Your cart is empty",
    notes: "Notes for the kitchen",
    placeOrder: "Place order",
    cancelOrder: "Cancel order",
    payCash: "Pay with cash",
    payOnline: "Pay online",
    call: "Call waiter",
    service: "Request service",
    noOrder: "No active order for this table",
    retry: "Retry",
    loading: "Loading",
    unavailable: "Sold out",
    required: "Required",
    quantity: "Quantity",
    close: "Close",
    pickup: "Drive-thru pickup",
    handover: "Handover code",
    here: "Confirm I am here",
    validate: "Checking price…",
    pricePending: "Choose options to see the price",
    clearCart: "Clear cart",
    remove: "Remove",
    vehicle: "Vehicle",
    color: "Color",
    model: "Model",
    plate: "Plate",
    fee: "Delivery fee",
    orderSent: "Order sent",
    backMenu: "Back to menu",
    presenceTitle: "Welcome to the table",
    presenceBody: "Confirm you are here, then order from the menu.",
    scanAgain: "Scan the table QR to start an order.",
  },
  ar: {
    language: "English",
    menu: "القائمة",
    cart: "السلة",
    checkout: "إتمام الطلب",
    track: "تتبع الطلب",
    add: "أضف للسلة",
    total: "المجموع",
    yourName: "اسمك",
    nameHint: "يظهر في سلة الطاولة المشتركة",
    pin: "رمز الطاولة",
    pinHint: "أدخل رمز الطاولة للانضمام من خارج الفرع",
    outside: "موقعك خارج الفرع. أدخل رمز الطاولة ثم انضم.",
    badPin: "الرمز غير صالح. اطلب الرمز الحالي من الفرع.",
    tableCodeFailed: "رمز الطاولة لا يعمل. يرجى طلب المساعدة من أحد الموظفين.",
    useLocation: "استخدم موقعي",
    join: "انضم إلى الطاولة",
    verifying: "جار التحقق من الطاولة…",
    emptyCart: "السلة فارغة",
    notes: "ملاحظات للمطبخ",
    placeOrder: "أرسل الطلب",
    cancelOrder: "إلغاء الطلب",
    payCash: "ادفع نقداً",
    payOnline: "ادفع إلكترونياً",
    call: "استدعاء النادل",
    service: "طلب خدمة",
    noOrder: "لا يوجد طلب نشط لهذه الطاولة",
    retry: "إعادة المحاولة",
    loading: "جار التحميل",
    unavailable: "غير متاح",
    required: "مطلوب",
    quantity: "الكمية",
    close: "إغلاق",
    pickup: "استلام من السيارة",
    handover: "رمز الاستلام",
    here: "تأكيد وجودي",
    validate: "جار حساب السعر…",
    pricePending: "اختر الإضافات لعرض السعر",
    clearCart: "تفريغ السلة",
    remove: "حذف",
    vehicle: "السيارة",
    color: "اللون",
    model: "الموديل",
    plate: "اللوحة",
    fee: "رسوم التوصيل",
    orderSent: "تم إرسال الطلب",
    backMenu: "العودة للقائمة",
    presenceTitle: "أهلاً بك على الطاولة",
    presenceBody: "أكد وجودك ثم اطلب من القائمة.",
    scanAgain: "امسح رمز الطاولة لبدء الطلب.",
  },
} as const;

export type GuestMessage = keyof (typeof guestCopy)["en"];
