import type { components } from "@/lib/api/schema";

type OrderStatus = components["schemas"]["OrderStatus"];

export const guestCopy = {
  en: {
    language: "العربية",
    menu: "Menu",
    cart: "Your cart",
    checkout: "Review your order",
    track: "Your order",
    add: "Add to order",
    added: "Added to your order",
    total: "Total",
    subtotal: "Subtotal",
    discount: "Discount",
    promo: "Promo code",
    promoHint: "Optional. The discount below is the one from the quote.",
    applyPromo: "Apply",
    serviceFee: "Service fee",
    tax: "Tax",
    yourName: "Your name",
    nameHint: "So everyone at the table knows whose dish is whose",
    pin: "Table PIN",
    pinHint: "Joining from outside? Our team can give you the table PIN.",
    outside: "Looks like you're a little way from us. Enter the table PIN and we'll get you seated.",
    badPin: "That PIN didn't work. Our team will happily give you the current one.",
    tableCodeFailed: "This table code isn't working. Please ask a staff member.",
    orderingPaused: "Ordering paused – please order at the counter",
    orderingPausedBody: "We can't take orders from your phone just now. Our team at the counter will happily look after you.",
    locationNote: "We couldn't confirm your location, so staff will confirm your order.",
    useLocation: "Use my location",
    locationHint: "Confirms you are at the table.",
    join: "Join this table",
    joinHint: "Order now. Our team confirms the order if we can't see that you're here.",
    havePin: "I have a table PIN",
    hidePin: "Hide the PIN",
    fewer: "Fewer",
    more: "More",
    sendRequest: "Send this request",
    serviceNote: "Add a note if it helps",
    verifying: "Getting your table ready…",
    emptyCart: "Your cart is empty. Take a look at the menu!",
    notes: "Anything the kitchen should know?",
    note: "Note",
    placeOrder: "Send my order",
    cancelOrder: "Cancel order",
    cancelTitle: "Cancel this order?",
    cancelBody: "We'll let the team know. You can always order again from the menu.",
    keepOrder: "Keep my order",
    cancelled: "Your order has been cancelled.",
    payCash: "Pay with cash",
    payOnline: "Pay online",
    paying: "One moment…",
    cashRequested: "Thank you! A team member will come to your table to collect payment.",
    paymentRequested: "Payment requested. A team member is on the way.",
    paid: "Paid",
    orderRejected: "Sorry, the restaurant couldn't accept this order.",
    startNewOrder: "Start a new order",
    enjoyMeal: "Enjoy your meal — you're all set.",
    amountDue: "Amount due",
    payAtCounter: "Please pay at the counter. We'll close the order once the payment is taken.",
    orderElse: "Order something else",
    sessionGone: "Your table session ended. Let's get you back to the table.",
    rejoin: "Rejoin table",
    rejoining: "Getting you back to the table…",
    payAfterConfirm: "You can pay as soon as our team confirms your order.",
    confirmTable: "A staff member needs to confirm your table first. They'll be with you shortly.",
    activeOrderOpen: "You already have an order with us. Here it is.",
    call: "Call a waiter",
    service: "Ask for help",
    noOrder: "You don't have an open order yet.",
    orderRef: "Order",
    table: "Table",
    retry: "Try again",
    oops: "Sorry, something went wrong. Please try again.",
    oopsTitle: "Sorry about that",
    loading: "One moment…",
    unavailable: "Sold out",
    required: "Required",
    chooseRequired: "Choose {name}. This choice is required.",
    quantity: "Quantity",
    close: "Close",
    pickup: "Drive-thru pickup",
    handover: "Pickup code",
    here: "I'm at the table",
    hereThanks: "Thanks! We know you're here.",
    validate: "Working out the price…",
    pricePending: "Choose your options to see the price",
    clearCart: "Clear cart",
    remove: "Remove",
    vehicle: "Your car",
    color: "Color",
    model: "Model",
    plate: "Plate",
    fee: "Delivery fee",
    orderSent: "Thank you! Your order is with our team.",
    payAtWindow: "Pay at the window",
    preparing: "We're preparing your order.",
    pickupCodeReady: "Your pickup code",
    orderCancelled: "This order was cancelled.",
    orderingTooFast: "You're ordering a bit fast. Please wait a minute and try again.",
    enjoyOrder: "Enjoy your order!",
    showOrderNumber: "Show your order number at the window and we'll hand it over.",
    placeAnother: "Place another order",
    backMenu: "Back to the menu",
    presenceTitle: "Welcome! Let's get you seated",
    presenceBody: "Join your table and order whenever you're ready.",
    scanAgain: "Scan the QR code on your table to get started.",
  },
  ar: {
    language: "English",
    menu: "القائمة",
    cart: "سلتك",
    checkout: "مراجعة طلبك",
    track: "طلبك",
    add: "أضف إلى الطلب",
    added: "أضفناه إلى طلبك",
    total: "المجموع",
    subtotal: "المجموع الفرعي",
    discount: "الخصم",
    promo: "رمز الخصم",
    promoHint: "اختياري. الخصم أدناه هو الخصم الذي أعاده التسعير.",
    applyPromo: "تطبيق",
    serviceFee: "رسوم الخدمة",
    tax: "الضريبة",
    yourName: "اسمك",
    nameHint: "ليعرف الجميع على الطاولة طبق كل شخص",
    pin: "رمز الطاولة",
    pinHint: "تنضم من خارج المطعم؟ فريقنا يسعده إعطاؤك رمز الطاولة.",
    outside: "يبدو أنك بعيد عنا قليلاً. أدخل رمز الطاولة وسنجهز لك مكانك.",
    badPin: "هذا الرمز لم يعمل. فريقنا يسعده إعطاؤك الرمز الحالي.",
    tableCodeFailed: "رمز الطاولة لا يعمل. يرجى طلب المساعدة من أحد الموظفين.",
    orderingPaused: "الطلب متوقف مؤقتاً – يرجى الطلب من الكاشير",
    orderingPausedBody: "لا يمكننا استلام الطلبات من هاتفك الآن. سيسعد فريقنا عند الكاشير بخدمتك.",
    locationNote: "لم نتمكن من تأكيد موقعك، لذا سيؤكد فريقنا طلبك.",
    useLocation: "استخدم موقعي",
    locationHint: "يؤكد أنك على الطاولة.",
    join: "انضم إلى الطاولة",
    joinHint: "اطلب الآن. يؤكد فريقنا الطلب إذا لم نستطع التأكد من وجودك هنا.",
    havePin: "لدي رمز الطاولة",
    hidePin: "إخفاء الرمز",
    fewer: "أقل",
    more: "أكثر",
    sendRequest: "أرسل هذا الطلب",
    serviceNote: "أضف ملاحظة إذا ساعدت",
    verifying: "نجهز طاولتك…",
    emptyCart: "سلتك فارغة. ألقِ نظرة على القائمة!",
    notes: "هل هناك ما يجب أن يعرفه المطبخ؟",
    note: "ملاحظة",
    placeOrder: "أرسل طلبي",
    cancelOrder: "إلغاء الطلب",
    cancelTitle: "إلغاء هذا الطلب؟",
    cancelBody: "سنبلغ الفريق. يمكنك الطلب مجدداً من القائمة في أي وقت.",
    keepOrder: "أبقِ طلبي",
    cancelled: "تم إلغاء طلبك.",
    payCash: "ادفع نقداً",
    payOnline: "ادفع إلكترونياً",
    paying: "لحظة من فضلك…",
    cashRequested: "شكراً لك! سيأتي أحد أفراد فريقنا إلى طاولتك لاستلام المبلغ.",
    paymentRequested: "تم طلب الدفع. أحد أفراد الفريق في الطريق إليك.",
    paid: "مدفوع",
    orderRejected: "عذراً، لم يتمكن المطعم من قبول هذا الطلب.",
    startNewOrder: "ابدأ طلباً جديداً",
    enjoyMeal: "بالهناء والشفاء — كل شيء تمام.",
    amountDue: "المبلغ المستحق",
    payAtCounter: "يُرجى الدفع عند الكاشير. سنغلق الطلب بعد استلام المبلغ.",
    orderElse: "اطلب شيئاً آخر",
    sessionGone: "انتهت جلسة الطاولة. لنعدك إلى طاولتك.",
    rejoin: "العودة إلى الطاولة",
    rejoining: "نعيدك إلى الطاولة…",
    payAfterConfirm: "يمكنك الدفع فور تأكيد فريقنا لطلبك.",
    confirmTable: "يحتاج أحد الموظفين إلى تأكيد طاولتك أولاً. سيكون معك خلال لحظات.",
    activeOrderOpen: "لديك طلب مفتوح معنا بالفعل. ها هو.",
    call: "استدعاء النادل",
    service: "اطلب المساعدة",
    noOrder: "ليس لديك طلب مفتوح بعد.",
    orderRef: "الطلب",
    table: "طاولة",
    retry: "حاول مجدداً",
    oops: "عذراً، حدث خطأ ما. يرجى المحاولة مجدداً.",
    oopsTitle: "نعتذر عن ذلك",
    loading: "لحظة من فضلك…",
    unavailable: "نفدت الكمية",
    required: "مطلوب",
    chooseRequired: "اختر {name}. هذا الاختيار مطلوب.",
    quantity: "الكمية",
    close: "إغلاق",
    pickup: "الاستلام من السيارة",
    handover: "رمز الاستلام",
    here: "أنا على الطاولة",
    hereThanks: "شكراً! عرفنا أنك هنا.",
    validate: "نحسب السعر…",
    pricePending: "اختر الإضافات لعرض السعر",
    clearCart: "تفريغ السلة",
    remove: "حذف",
    vehicle: "سيارتك",
    color: "اللون",
    model: "الموديل",
    plate: "اللوحة",
    fee: "رسوم التوصيل",
    orderSent: "شكراً لك! طلبك الآن مع فريقنا.",
    payAtWindow: "الدفع عند النافذة",
    preparing: "نحن نحضّر طلبك.",
    pickupCodeReady: "رمز الاستلام",
    orderCancelled: "تم إلغاء هذا الطلب.",
    orderingTooFast: "أنت تطلب بسرعة. يرجى الانتظار دقيقة ثم المحاولة مجدداً.",
    enjoyOrder: "بالهناء والشفاء!",
    showOrderNumber: "اعرض رقم طلبك عند النافذة وسنسلّمه لك.",
    placeAnother: "اطلب طلباً آخر",
    backMenu: "العودة إلى القائمة",
    presenceTitle: "أهلاً بك! لنجهز لك طاولتك",
    presenceBody: "انضم إلى طاولتك واطلب متى كنت مستعداً.",
    scanAgain: "امسح رمز QR الموجود على طاولتك للبدء.",
  },
} as const;

export type GuestMessage = keyof (typeof guestCopy)["en"];

export const guestStatus: Record<keyof typeof guestCopy, Record<OrderStatus, string>> = {
  en: {
    DRAFT: "Getting your order ready",
    PENDING_STAFF_CONFIRMATION: "Waiting for staff to confirm your order",
    SUBMITTED: "Order confirmed",
    PREPARING: "The kitchen is preparing your order",
    READY: "Your order is ready",
    SERVED: "Served. Enjoy your meal!",
    DELIVERED: "Served. Enjoy your meal!",
    PAID: "Paid. Thank you!",
    CLOSED: "All done. Thanks for dining with us!",
    CANCELLED: "Sorry, the restaurant couldn't accept this order.",
  },
  ar: {
    DRAFT: "نجهز طلبك",
    PENDING_STAFF_CONFIRMATION: "بانتظار تأكيد الفريق لطلبك",
    SUBMITTED: "تم تأكيد الطلب",
    PREPARING: "المطبخ يحضّر طلبك",
    READY: "طلبك جاهز",
    SERVED: "تم التقديم. بالهناء والشفاء!",
    DELIVERED: "تم التقديم. بالهناء والشفاء!",
    PAID: "تم الدفع. شكراً لك!",
    CLOSED: "انتهينا. شكراً لزيارتك!",
    CANCELLED: "عذراً، لم يتمكن المطعم من قبول هذا الطلب.",
  },
};

export const guestServiceType: Record<keyof typeof guestCopy, Record<components["schemas"]["ServiceRequestType"], string>> = {
  en: {
    WAITER_CALL: "Call a waiter",
    WATER: "Water",
    WATER_REFILL: "Water refill",
    CUTLERY: "Cutlery",
    NAPKINS: "Napkins",
    PLATES: "Plates",
    PACK_LEFTOVERS: "Pack leftovers",
    BILL_REQUEST: "Ask for the bill",
    TAKEAWAY_ORDER: "Takeaway",
    OTHER: "Something else",
  },
  ar: {
    WAITER_CALL: "استدعاء النادل",
    WATER: "ماء",
    WATER_REFILL: "إعادة ملء الماء",
    CUTLERY: "أدوات المائدة",
    NAPKINS: "مناديل",
    PLATES: "أطباق",
    PACK_LEFTOVERS: "تغليف المتبقي",
    BILL_REQUEST: "طلب الحساب",
    TAKEAWAY_ORDER: "طلب للخارج",
    OTHER: "طلب آخر",
  },
};

export const guestServiceStatus: Record<keyof typeof guestCopy, Record<components["schemas"]["ServiceRequestStatus"], string>> = {
  en: {
    PENDING: "On the way",
    ACKNOWLEDGED: "Seen by the team",
    COMPLETED: "Done",
    DISMISSED: "Closed",
  },
  ar: {
    PENDING: "في الطريق",
    ACKNOWLEDGED: "رآه الفريق",
    COMPLETED: "تم",
    DISMISSED: "أُغلق",
  },
};

/** Statuses from which the guest may pay: the team has confirmed the order and it isn't finished. */
export const PAYABLE_STATUSES: ReadonlySet<OrderStatus> = new Set([
  "SUBMITTED",
  "PREPARING",
  "READY",
  "SERVED",
  "DELIVERED",
]);
